image: rocker/geospatial
test:
   script:
    - R -e 'install.packages(c("data.table", "devtools", "adehabitatHR", "igraph"))'
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
    - R -e 'devtools::test()'
