image: registry.gitlab.com/robit.a/spatsoc
test:
   script:
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
    - R -e 'devtools::test(stop_on_failure = TRUE)'
